[{assign var=bShowStandard value=true}]
[{if $aVariantSelections && $aVariantSelections.selections}]
    [{if $aVariantSelections.selections|@count == 1}]
        [{assign var=bShowStandard value=false}]
    [{/if}]
[{/if}]
[{if $bShowStandard}]
    [{$smarty.block.parent}]
[{/if}]